kind: pipeline
type: docker
name: order-tracking

steps:
  - name: python 3.11
    image: python:3.11
    environment:
      ENV_STATE: development
      DATABASE_URL: 'sqlite:///storage/test.db'
      LOG_LEVEL: DEBUG
    commands:
    - pip install poetry
    - poetry install --with test
    - make citest

  - name: notify
    image: drillster/drone-email
    settings:
      host: smtp.metaorg.com
      port: 25
      from: metaorg@mail.com
      recipients: [drone-aguada@mail.com]
      recipients_only: true
      attachment: build-result.xml
      skip_verify: true

trigger:
  event:
  - pull_request
